# Uso del módulo Numpy
### creado por Juan Pablo Requez - juanrequez@gmail.com

Primero debe importarse el *módulo numpy*.

Es importante que el módulo numpy debe estar instalado

In [1]:
import numpy as np

### crear dos vectores

In [2]:
#crear un vector fila (esto no es verdaderamente un vector fila, sino un vector unidimensional,
#que en numpy son tratados diferente)
vector1=np.array([1,2,3,4])

In [3]:
#crear un vector columna
vector2=np.array([[1],[2],[3],[4]])

In [4]:
vector1

array([1, 2, 3, 4])

In [5]:
vector2

array([[1],
       [2],
       [3],
       [4]])

In [6]:
#Crear una matriz cuadrada de 3x3
matriz1=np.array([[1,2,3],[-1,0,-1],[0,3,2]])

In [7]:
#crear una matriz rectangular de 3x2
matriz2=np.array([[3,2],[-6,-1],[2,7]])

In [8]:
matriz1

array([[ 1,  2,  3],
       [-1,  0, -1],
       [ 0,  3,  2]])

In [9]:
matriz2

array([[ 3,  2],
       [-6, -1],
       [ 2,  7]])

La dimensión de cada vector y matriz es

In [10]:
vector1.ndim

1

In [11]:
vector2.ndim

2

In [12]:
matriz1.ndim

2

In [13]:
matriz2.ndim

2

Puede verse la forma de cada objeto, es decir, las dimensiones verdaderas

In [14]:
vector1.shape

(4,)

In [15]:
vector2.shape

(4, 1)

In [16]:
matriz1.shape

(3, 3)

In [17]:
matriz2.shape

(3, 2)

Se puede observar el tipo los objetos creados

In [18]:
vector1.dtype

dtype('int32')

## Creación intrínseca de Arrays

In [19]:
#Crear una matriz de ceros de 3x3
matrizcero=np.zeros([3,3])
#Crear una matriz de unos de 4x5
matrizunos=np.ones([3,4])
#Crear una matriz identidad de tamaño 5
matrizidentidad=np.identity(5)
#crear un vector con valores desde 0 hasta 10 con 5 divisiones
rvector=np.linspace(0,10,5)


In [20]:
matrizcero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
matrizunos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
matrizidentidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
rvector

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Operaciones elemento a elemento

In [24]:
rvector+5

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [25]:
np.sin(rvector)

array([ 0.        ,  0.59847214, -0.95892427,  0.93799998, -0.54402111])

In [26]:
np.exp(rvector)

array([1.00000000e+00, 1.21824940e+01, 1.48413159e+02, 1.80804241e+03,
       2.20264658e+04])

## Operaciones matriciales

In [27]:
np.dot(matriz1,matriz2)

array([[ -3,  21],
       [ -5,  -9],
       [-14,  11]])

In [28]:
#La operación de inversa de una matriz se calcula como sigue
np.linalg.inv(matriz1)

array([[-1.5, -2.5,  1. ],
       [-1. , -1. ,  1. ],
       [ 1.5,  1.5, -1. ]])

In [29]:
np.dot(vector2,[vector1])

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [30]:
np.inner(vector1,np.transpose(vector2))

array([30])

In [31]:
np.dot(vector1,vector2)

array([30])

In [32]:
# Puede realizarse multiplicación matricial usando el símbolo @
vector2 @ [vector1]

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

## Cambiar arreglos de forma

In [33]:
#Definamos un arreglo simple, por ejemplo
data=np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [34]:
#Observemos que podemos convertirlo en un vector de 1 fila y 4 columnas
np.reshape(data,(1,4))

array([[1, 2, 3, 4]])

In [35]:
np.reshape(data,(1,4)).shape

(1, 4)

In [36]:
#tambien podemos convertirlo en un vector fila (que es esencialmente el mismo vector, pero en otra configuración)
np.reshape(data,(4))

array([1, 2, 3, 4])

In [37]:
np.reshape(data,(4)).shape


(4,)

In [38]:
#y si queremos un vector columna,
np.reshape(data,(4,1))

array([[1],
       [2],
       [3],
       [4]])

In [39]:
np.reshape(data,(4,1)).shape

(4, 1)